#!/bin/sh

GIT_WORK_TREE=/home/nisarg/NCSU/Fall15/DevOps/Devops-AdvancedDocker/deploy/blue-www/ git checkout -f

echo "Pulling the latest image from the registry"
docker pull localhost:5000/ncsu:latest  
echo "Stop and restart Blue slice container"
docker stop blue-app  
docker rm blue-app
docker rmi localhost:5000/ncsu:current-blue  
docker tag localhost:5000/ncsu:latest localhost:5000/ncsu:current-blue	
docker run -p 50100:8080 -d --name blue-app localhost:5000/ncsu:latest