#!/bin/sh

# This is the script that will be triggered upon a `git push` to the green repo.
# The script stops the currently running application on the green container and deploys the latest version of the application.

sudo docker pull localhost:5000/ncsu:latest
sudo docker stop green_app
sudo docker rm green_app
sudo docker rmi localhost:5000/ncsu:current_green  
sudo docker tag localhost:5000/ncsu:latest localhost:5000/ncsu:current_green
sudo docker run -p 50101:8080 -d --name green_app localhost:5000/ncsu:current_green

